### ISSUE TITLE
Bug w wersji 1.9.0

### ISSUE THREAD

**Issue by MrFynn** [lkosson/profak#21]
Program otwiera się na ostatnio wybranej pozycji z głównego menu po lewej stronie. Gdy otworzymy formularz z sekcji serwisowe -> konfiguracja następnie zamkniemy go i wyjdziemy z programu, po ponownym odpaleniu program będzie zfreezowany i wyrzuci błą po jakimś czasie:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.ConnectionBeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.BeginTransaction()
   at ProFak.Transakcja..ctor(Baza baza) in C:\Users\Mike\source\repos\profak\DB\Transakcja.cs:line 27
   at ProFak.UI.Kontekst.Transakcja() in C:\Users\Mike\source\repos\profak\UI\Kontekst.cs:line 51
   at ProFak.UI.GlowneOkno.ZapiszStanPozycji(TreeNode treeNode) in C:\Users\Mike\source\repos\profak\UI\GlowneOkno.cs:line 212
   at ProFak.UI.GlowneOkno.menu_AfterSelect(Object sender, TreeViewEventArgs e) in C:\Users\Mike\source\repos\profak\UI\GlowneOkno.cs:line 105
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam) 

![image](https://github.com/user-attachments/assets/4c0dbc23-340c-4163-bd05-b29cb851d823)

**Comment by lkosson** [comment]
Poprawione w wersji 1.9.1.
